# Generated by Django 2.1.7 on 2019-03-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='last_update',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assetdatevalue',
            name='volume',
            field=models.BigIntegerField(),
        ),
    ]
