# Generated by Django 2.1.7 on 2019-03-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20190307_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search', models.CharField(max_length=100)),
                ('search_date', models.DateField()),
            ],
        ),
    ]
