# Generated by Django 2.1.7 on 2019-03-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_previoussearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previoussearch',
            name='search_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
